# On startup, try to connect that many seconds before
# giving up and terminating with a fatal error
initial_connection_timeout = 60

# Address of the PV system
e3dc = { host = "127.0.0.1", port = 5201 }

# Address of the EV charging station
wallbox = { host = "127.0.0.1", port = 5202 }

# OnePhase or ThreePhase, this is used to compute the power per amp
phases = "ThreePhase"

# The minimum current to use when charging
min_amp = 8

# The maximum current supported by the EV charging station
max_amp = 16

# After a vehicle is connected and starts to charge, use the min_amp
# setting regardless of the PV power available for this many seconds.
# The primary purpose for this setting is that some vehicles get
# confused when they are signalled that no power is available
# immediately after being connected. 180 seconds should be a
# reasonable default.
initial_phase_duration = 180

# The voltage per phase, used to compute ther power per amp
phase_voltage = 230

# If there is some excessive power available from the PV system,
# we'd slowly increase the charging power by one amp at a time.
# This setting specifies how many additional watts have to be
# available before the increase happens.
# For example, on a 230V three phase system, increasing the
# charging current from 8 amps to 9 amps would increase the
# charging power from 5520 Watts to 6210 Watts, the difference
# being 690 Watts. With a hysteresis of 200 Watts, the amount
# of surplus power has to be 890 Watts before the increase
# from 8 Amps to 9 Amps happens.
hysteresis_watts = 200